name: Firebase Continuous Deployment Prod Env

on:
  push:
    branches: [ master ]

jobs:
  deploy: 
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_API_KEY =${{ secrets.REACT_APP_API_KEY }} >> .env
          echo REACT_APP_AUTH_DOMAIN =${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
          echo REACT_APP_PROJECT_ID =${{ secrets.REACT_APP_PROJECT_ID }} >> .env
          echo REACT_APP_STORAGE_BUCKET =${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
          echo REACT_APP_MESSAGING_SENDER_ID =${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_APP_ID =${{ secrets.REACT_APP_APP_ID }} >> .env
          echo REACT_APP_MEASUREMENT_ID =${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}